cuv1=str(input('Introduceti primul cuvant: '))
cuv2=str(input('Introduceti al doilea cuvant: '))
cuv3=str(input('Introduceti al treilea cuvant: '))
cuv4=str(input('Introduceti al patrulea cuvant: '))
print(f'Fraza ce sa primit: {cuv1} {cuv2} {cuv3} {cuv4}.')
